version: v1

labels:
  - label: "feature"
    sync: true
    matcher:
      title: "^feat: .*"
      commits: "^feat: .*"
      body: "(\\n|.)*- \\[x\\] feature(\\n|.)*"

  - label: "fix"
    sync: true
    matcher:
      title: "^fix: .*"
      commits: "^fix: .*"
      body: "(\\n|.)*- \\[x\\] (fix|bug)(\\n|.)*"

  - label: "chore"
    sync: true
    matcher:
      title: "^chore: .*"
      commits: "^chore: .*"
      body: "(\\n|.)*- \\[x\\] chore(\\n|.)*"
      files: [ ".github/*" ]

  - label: "documentation"
    sync: true
    matcher:
      title: "^docs: .*"
      commits: "^docs: .*"
      files: [ "*.md", "doc.go" ]

checks:
  - context: "Semantic Pull Request"
    url: "https://github.com/Fishwaldo/mouthpiece/blob/master/.github/labeler.yml"
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for merge.
    labels:
      any:
        - 'feature'
        - 'fix'
        - 'chore'
        - 'documentation'
        - 'dependencies'
