/*
	MIT License

	Copyright (c) 2021 Justin Hammond

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/Fishwaldo/mouthpiece/pkg/ent/app"
	"github.com/Fishwaldo/mouthpiece/pkg/ent/tenant"
	"github.com/Fishwaldo/mouthpiece/pkg/validate"
)

// App is the model entity for the App schema.
type App struct {
	config `default:"-" doc:"-" enum:"-" gorm:"-" json:"-" pattern:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int `json:"tenant_id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty" doc:"Application Name" pattern:"^[a-z0-9]+$" gorm:"unique;uniqueIndex"`
	// Status holds the value of the "Status" field.
	Status app.Status `json:"Status,omitempty" doc:"Status of Application" enum:"Enabled,Disabled" default:"Enabled"`
	// Description holds the value of the "Description" field.
	Description string `json:"Description,omitempty" doc:"Description of Application"`
	// Icon holds the value of the "icon" field.
	Icon string `json:"icon,omitempty" doc:"Icon of Application"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty" doc:"URL of Application"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AppQuery when eager-loading is set.
	Edges AppEdges `json:"edges"`
}

// AppEdges holds the relations/edges for other nodes in the graph.
type AppEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*Message `json:"messages,omitempty"`
	// Filters holds the value of the filters edge.
	Filters []*Filter `json:"filters,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// TransportRecipients holds the value of the TransportRecipients edge.
	TransportRecipients []*TransportRecipient `json:"TransportRecipients,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AppEdges) TenantOrErr() (*Tenant, error) {
	if e.loadedTypes[0] {
		if e.Tenant == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: tenant.Label}
		}
		return e.Tenant, nil
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) MessagesOrErr() ([]*Message, error) {
	if e.loadedTypes[1] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// FiltersOrErr returns the Filters value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) FiltersOrErr() ([]*Filter, error) {
	if e.loadedTypes[2] {
		return e.Filters, nil
	}
	return nil, &NotLoadedError{edge: "filters"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[3] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// TransportRecipientsOrErr returns the TransportRecipients value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) TransportRecipientsOrErr() ([]*TransportRecipient, error) {
	if e.loadedTypes[4] {
		return e.TransportRecipients, nil
	}
	return nil, &NotLoadedError{edge: "TransportRecipients"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*App) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case app.FieldID, app.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case app.FieldName, app.FieldStatus, app.FieldDescription, app.FieldIcon, app.FieldURL:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type App", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the App fields.
func (a *App) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case app.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case app.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				a.TenantID = int(value.Int64)
			}
		case app.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case app.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Status", values[i])
			} else if value.Valid {
				a.Status = app.Status(value.String)
			}
		case app.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Description", values[i])
			} else if value.Valid {
				a.Description = value.String
			}
		case app.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				a.Icon = value.String
			}
		case app.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				a.URL = value.String
			}
		}
	}
	return nil
}

// QueryTenant queries the "tenant" edge of the App entity.
func (a *App) QueryTenant() *TenantQuery {
	return (&AppClient{config: a.config}).QueryTenant(a)
}

// QueryMessages queries the "messages" edge of the App entity.
func (a *App) QueryMessages() *MessageQuery {
	return (&AppClient{config: a.config}).QueryMessages(a)
}

// QueryFilters queries the "filters" edge of the App entity.
func (a *App) QueryFilters() *FilterQuery {
	return (&AppClient{config: a.config}).QueryFilters(a)
}

// QueryGroups queries the "groups" edge of the App entity.
func (a *App) QueryGroups() *GroupQuery {
	return (&AppClient{config: a.config}).QueryGroups(a)
}

// QueryTransportRecipients queries the "TransportRecipients" edge of the App entity.
func (a *App) QueryTransportRecipients() *TransportRecipientQuery {
	return (&AppClient{config: a.config}).QueryTransportRecipients(a)
}

// Update returns a builder for updating this App.
// Note that you need to call App.Unwrap() before calling this method if this App
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *App) Update() *AppUpdateOne {
	return (&AppClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the App entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *App) Unwrap() *App {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: App is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *App) String() string {
	var builder strings.Builder
	builder.WriteString("App(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", a.TenantID))
	builder.WriteString(", ")
	builder.WriteString("Name=")
	builder.WriteString(a.Name)
	builder.WriteString(", ")
	builder.WriteString("Status=")
	builder.WriteString(fmt.Sprintf("%v", a.Status))
	builder.WriteString(", ")
	builder.WriteString("Description=")
	builder.WriteString(a.Description)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(a.Icon)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(a.URL)
	builder.WriteByte(')')
	return builder.String()
}

func (a *App) ValidateApp() error {
	if err := validate.Get().Struct(a); err != nil {
		return err
	}
	return nil
}

// Apps is a parsable slice of App.
type Apps []*App

func (a Apps) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
