/*
	MIT License

	Copyright (c) 2021 Justin Hammond

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mouthpiece/pkg/ent/dbapp"
	"github.com/Fishwaldo/mouthpiece/pkg/ent/dbfilter"
	"github.com/Fishwaldo/mouthpiece/pkg/ent/dbgroup"
	"github.com/Fishwaldo/mouthpiece/pkg/ent/dbmessage"
	"github.com/Fishwaldo/mouthpiece/pkg/ent/predicate"
	"github.com/Fishwaldo/mouthpiece/pkg/ent/tenant"
)

// DbAppQuery is the builder for querying DbApp entities.
type DbAppQuery struct {
	config
	limit        *int
	offset       *int
	unique       *bool
	order        []OrderFunc
	fields       []string
	predicates   []predicate.DbApp
	withTenant   *TenantQuery
	withMessages *DbMessageQuery
	withFilters  *DbFilterQuery
	withGroups   *DbGroupQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DbAppQuery builder.
func (daq *DbAppQuery) Where(ps ...predicate.DbApp) *DbAppQuery {
	daq.predicates = append(daq.predicates, ps...)
	return daq
}

// Limit adds a limit step to the query.
func (daq *DbAppQuery) Limit(limit int) *DbAppQuery {
	daq.limit = &limit
	return daq
}

// Offset adds an offset step to the query.
func (daq *DbAppQuery) Offset(offset int) *DbAppQuery {
	daq.offset = &offset
	return daq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (daq *DbAppQuery) Unique(unique bool) *DbAppQuery {
	daq.unique = &unique
	return daq
}

// Order adds an order step to the query.
func (daq *DbAppQuery) Order(o ...OrderFunc) *DbAppQuery {
	daq.order = append(daq.order, o...)
	return daq
}

// QueryTenant chains the current query on the "tenant" edge.
func (daq *DbAppQuery) QueryTenant() *TenantQuery {
	query := &TenantQuery{config: daq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := daq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := daq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dbapp.Table, dbapp.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, dbapp.TenantTable, dbapp.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(daq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMessages chains the current query on the "messages" edge.
func (daq *DbAppQuery) QueryMessages() *DbMessageQuery {
	query := &DbMessageQuery{config: daq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := daq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := daq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dbapp.Table, dbapp.FieldID, selector),
			sqlgraph.To(dbmessage.Table, dbmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dbapp.MessagesTable, dbapp.MessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(daq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFilters chains the current query on the "filters" edge.
func (daq *DbAppQuery) QueryFilters() *DbFilterQuery {
	query := &DbFilterQuery{config: daq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := daq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := daq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dbapp.Table, dbapp.FieldID, selector),
			sqlgraph.To(dbfilter.Table, dbfilter.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, dbapp.FiltersTable, dbapp.FiltersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(daq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroups chains the current query on the "groups" edge.
func (daq *DbAppQuery) QueryGroups() *DbGroupQuery {
	query := &DbGroupQuery{config: daq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := daq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := daq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dbapp.Table, dbapp.FieldID, selector),
			sqlgraph.To(dbgroup.Table, dbgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, dbapp.GroupsTable, dbapp.GroupsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(daq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DbApp entity from the query.
// Returns a *NotFoundError when no DbApp was found.
func (daq *DbAppQuery) First(ctx context.Context) (*DbApp, error) {
	nodes, err := daq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dbapp.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (daq *DbAppQuery) FirstX(ctx context.Context) *DbApp {
	node, err := daq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DbApp ID from the query.
// Returns a *NotFoundError when no DbApp ID was found.
func (daq *DbAppQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = daq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dbapp.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (daq *DbAppQuery) FirstIDX(ctx context.Context) int {
	id, err := daq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DbApp entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DbApp entity is found.
// Returns a *NotFoundError when no DbApp entities are found.
func (daq *DbAppQuery) Only(ctx context.Context) (*DbApp, error) {
	nodes, err := daq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dbapp.Label}
	default:
		return nil, &NotSingularError{dbapp.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (daq *DbAppQuery) OnlyX(ctx context.Context) *DbApp {
	node, err := daq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DbApp ID in the query.
// Returns a *NotSingularError when more than one DbApp ID is found.
// Returns a *NotFoundError when no entities are found.
func (daq *DbAppQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = daq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dbapp.Label}
	default:
		err = &NotSingularError{dbapp.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (daq *DbAppQuery) OnlyIDX(ctx context.Context) int {
	id, err := daq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DbApps.
func (daq *DbAppQuery) All(ctx context.Context) ([]*DbApp, error) {
	if err := daq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return daq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (daq *DbAppQuery) AllX(ctx context.Context) []*DbApp {
	nodes, err := daq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DbApp IDs.
func (daq *DbAppQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := daq.Select(dbapp.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (daq *DbAppQuery) IDsX(ctx context.Context) []int {
	ids, err := daq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (daq *DbAppQuery) Count(ctx context.Context) (int, error) {
	if err := daq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return daq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (daq *DbAppQuery) CountX(ctx context.Context) int {
	count, err := daq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (daq *DbAppQuery) Exist(ctx context.Context) (bool, error) {
	if err := daq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return daq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (daq *DbAppQuery) ExistX(ctx context.Context) bool {
	exist, err := daq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DbAppQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (daq *DbAppQuery) Clone() *DbAppQuery {
	if daq == nil {
		return nil
	}
	return &DbAppQuery{
		config:       daq.config,
		limit:        daq.limit,
		offset:       daq.offset,
		order:        append([]OrderFunc{}, daq.order...),
		predicates:   append([]predicate.DbApp{}, daq.predicates...),
		withTenant:   daq.withTenant.Clone(),
		withMessages: daq.withMessages.Clone(),
		withFilters:  daq.withFilters.Clone(),
		withGroups:   daq.withGroups.Clone(),
		// clone intermediate query.
		sql:    daq.sql.Clone(),
		path:   daq.path,
		unique: daq.unique,
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (daq *DbAppQuery) WithTenant(opts ...func(*TenantQuery)) *DbAppQuery {
	query := &TenantQuery{config: daq.config}
	for _, opt := range opts {
		opt(query)
	}
	daq.withTenant = query
	return daq
}

// WithMessages tells the query-builder to eager-load the nodes that are connected to
// the "messages" edge. The optional arguments are used to configure the query builder of the edge.
func (daq *DbAppQuery) WithMessages(opts ...func(*DbMessageQuery)) *DbAppQuery {
	query := &DbMessageQuery{config: daq.config}
	for _, opt := range opts {
		opt(query)
	}
	daq.withMessages = query
	return daq
}

// WithFilters tells the query-builder to eager-load the nodes that are connected to
// the "filters" edge. The optional arguments are used to configure the query builder of the edge.
func (daq *DbAppQuery) WithFilters(opts ...func(*DbFilterQuery)) *DbAppQuery {
	query := &DbFilterQuery{config: daq.config}
	for _, opt := range opts {
		opt(query)
	}
	daq.withFilters = query
	return daq
}

// WithGroups tells the query-builder to eager-load the nodes that are connected to
// the "groups" edge. The optional arguments are used to configure the query builder of the edge.
func (daq *DbAppQuery) WithGroups(opts ...func(*DbGroupQuery)) *DbAppQuery {
	query := &DbGroupQuery{config: daq.config}
	for _, opt := range opts {
		opt(query)
	}
	daq.withGroups = query
	return daq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID int `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DbApp.Query().
//		GroupBy(dbapp.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (daq *DbAppQuery) GroupBy(field string, fields ...string) *DbAppGroupBy {
	grbuild := &DbAppGroupBy{config: daq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := daq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return daq.sqlQuery(ctx), nil
	}
	grbuild.label = dbapp.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID int `json:"tenant_id,omitempty"`
//	}
//
//	client.DbApp.Query().
//		Select(dbapp.FieldTenantID).
//		Scan(ctx, &v)
//
func (daq *DbAppQuery) Select(fields ...string) *DbAppSelect {
	daq.fields = append(daq.fields, fields...)
	selbuild := &DbAppSelect{DbAppQuery: daq}
	selbuild.label = dbapp.Label
	selbuild.flds, selbuild.scan = &daq.fields, selbuild.Scan
	return selbuild
}

func (daq *DbAppQuery) prepareQuery(ctx context.Context) error {
	for _, f := range daq.fields {
		if !dbapp.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if daq.path != nil {
		prev, err := daq.path(ctx)
		if err != nil {
			return err
		}
		daq.sql = prev
	}
	if dbapp.Policy == nil {
		return errors.New("ent: uninitialized dbapp.Policy (forgotten import ent/runtime?)")
	}
	if err := dbapp.Policy.EvalQuery(ctx, daq); err != nil {
		return err
	}
	return nil
}

func (daq *DbAppQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DbApp, error) {
	var (
		nodes       = []*DbApp{}
		_spec       = daq.querySpec()
		loadedTypes = [4]bool{
			daq.withTenant != nil,
			daq.withMessages != nil,
			daq.withFilters != nil,
			daq.withGroups != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*DbApp).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &DbApp{config: daq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, daq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := daq.withTenant; query != nil {
		if err := daq.loadTenant(ctx, query, nodes, nil,
			func(n *DbApp, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := daq.withMessages; query != nil {
		if err := daq.loadMessages(ctx, query, nodes,
			func(n *DbApp) { n.Edges.Messages = []*DbMessage{} },
			func(n *DbApp, e *DbMessage) { n.Edges.Messages = append(n.Edges.Messages, e) }); err != nil {
			return nil, err
		}
	}
	if query := daq.withFilters; query != nil {
		if err := daq.loadFilters(ctx, query, nodes,
			func(n *DbApp) { n.Edges.Filters = []*DbFilter{} },
			func(n *DbApp, e *DbFilter) { n.Edges.Filters = append(n.Edges.Filters, e) }); err != nil {
			return nil, err
		}
	}
	if query := daq.withGroups; query != nil {
		if err := daq.loadGroups(ctx, query, nodes,
			func(n *DbApp) { n.Edges.Groups = []*DbGroup{} },
			func(n *DbApp, e *DbGroup) { n.Edges.Groups = append(n.Edges.Groups, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (daq *DbAppQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*DbApp, init func(*DbApp), assign func(*DbApp, *Tenant)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DbApp)
	for i := range nodes {
		fk := nodes[i].TenantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (daq *DbAppQuery) loadMessages(ctx context.Context, query *DbMessageQuery, nodes []*DbApp, init func(*DbApp), assign func(*DbApp, *DbMessage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DbApp)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DbMessage(func(s *sql.Selector) {
		s.Where(sql.InValues(dbapp.MessagesColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.db_app_messages
		if fk == nil {
			return fmt.Errorf(`foreign-key "db_app_messages" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "db_app_messages" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (daq *DbAppQuery) loadFilters(ctx context.Context, query *DbFilterQuery, nodes []*DbApp, init func(*DbApp), assign func(*DbApp, *DbFilter)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*DbApp)
	nids := make(map[int]map[*DbApp]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(dbapp.FiltersTable)
		s.Join(joinT).On(s.C(dbfilter.FieldID), joinT.C(dbapp.FiltersPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(dbapp.FiltersPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(dbapp.FiltersPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]interface{}, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]interface{}{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []interface{}) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*DbApp]struct{}{byID[outValue]: struct{}{}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "filters" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (daq *DbAppQuery) loadGroups(ctx context.Context, query *DbGroupQuery, nodes []*DbApp, init func(*DbApp), assign func(*DbApp, *DbGroup)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*DbApp)
	nids := make(map[int]map[*DbApp]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(dbapp.GroupsTable)
		s.Join(joinT).On(s.C(dbgroup.FieldID), joinT.C(dbapp.GroupsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(dbapp.GroupsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(dbapp.GroupsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]interface{}, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]interface{}{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []interface{}) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*DbApp]struct{}{byID[outValue]: struct{}{}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "groups" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (daq *DbAppQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := daq.querySpec()
	_spec.Node.Columns = daq.fields
	if len(daq.fields) > 0 {
		_spec.Unique = daq.unique != nil && *daq.unique
	}
	return sqlgraph.CountNodes(ctx, daq.driver, _spec)
}

func (daq *DbAppQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := daq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (daq *DbAppQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dbapp.Table,
			Columns: dbapp.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dbapp.FieldID,
			},
		},
		From:   daq.sql,
		Unique: true,
	}
	if unique := daq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := daq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dbapp.FieldID)
		for i := range fields {
			if fields[i] != dbapp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := daq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := daq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := daq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := daq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (daq *DbAppQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(daq.driver.Dialect())
	t1 := builder.Table(dbapp.Table)
	columns := daq.fields
	if len(columns) == 0 {
		columns = dbapp.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if daq.sql != nil {
		selector = daq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if daq.unique != nil && *daq.unique {
		selector.Distinct()
	}
	for _, p := range daq.predicates {
		p(selector)
	}
	for _, p := range daq.order {
		p(selector)
	}
	if offset := daq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := daq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DbAppGroupBy is the group-by builder for DbApp entities.
type DbAppGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dagb *DbAppGroupBy) Aggregate(fns ...AggregateFunc) *DbAppGroupBy {
	dagb.fns = append(dagb.fns, fns...)
	return dagb
}

// Scan applies the group-by query and scans the result into the given value.
func (dagb *DbAppGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := dagb.path(ctx)
	if err != nil {
		return err
	}
	dagb.sql = query
	return dagb.sqlScan(ctx, v)
}

func (dagb *DbAppGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range dagb.fields {
		if !dbapp.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := dagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dagb *DbAppGroupBy) sqlQuery() *sql.Selector {
	selector := dagb.sql.Select()
	aggregation := make([]string, 0, len(dagb.fns))
	for _, fn := range dagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(dagb.fields)+len(dagb.fns))
		for _, f := range dagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(dagb.fields...)...)
}

// DbAppSelect is the builder for selecting fields of DbApp entities.
type DbAppSelect struct {
	*DbAppQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (das *DbAppSelect) Scan(ctx context.Context, v interface{}) error {
	if err := das.prepareQuery(ctx); err != nil {
		return err
	}
	das.sql = das.DbAppQuery.sqlQuery(ctx)
	return das.sqlScan(ctx, v)
}

func (das *DbAppSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := das.sql.Query()
	if err := das.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
