on:
  push:
  pull_request:

name: Build
jobs:
    test:
        strategy:
            matrix:
                go-version: [ 1.18.x ]
                platform: [ ubuntu-latest, macos-latest, windows-latest ]
        runs-on: ${{ matrix.platform }}
        steps:
            -   name: Install Go
                if: success()
                uses: actions/setup-go@v1
                with:
                    go-version: ${{ matrix.go-version }}
            -   name: Checkout code
                uses: actions/checkout@v1
            -   name: Build 
                run: go build .
            -   name: Run tests
                run: go test -v -race ./...

    analyze:
        name: Analyze
        runs-on: ubuntu-latest   
        needs: [ test ]  
        permissions:
            actions: read
            contents: read
            security-events: write
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v1
          with:
            languages: go
        - name: Autobuild
          uses: github/codeql-action/autobuild@v1
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v1

    codecov:
        runs-on: ubuntu-latest
        needs: [ test ]
        steps:
            -   name: Install Go
                if: success()
                uses: actions/setup-go@v1
                with:
                    go-version: 1.18.x
            -   name: Checkout code
                uses: actions/checkout@v1
            -   name: Run tests
                run: go mod tidy && go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
            -   name: CodeCov
                uses: codecov/codecov-action@v2
